#server.port=8080

spring.profiles.active=dev

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:bookstore.p12
server.ssl.key-store-password=${SSL_PASSWORD}
server.ssl.key-alias=bookstore

server.port=8443

spring.web.resources.add-mappings=false

logging.file.name=application.log
